
---
- name: Deploy Jasper Reports - <%= projectNameUpperCase %>
  hosts: localhost
  connection: local
  collections:
    - polaris.deploy
  vars:
    jasper_server_instance: <%= jasperServerInstanceUpperCase %>
    jasper_project_name: <%= projectNameUpperCase %>
    jasper_ds_0_url: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_0_url') | default('') }}"
    jasper_ds_0_user: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_0_user') | default('') }}"
    jasper_ds_0_password: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_0_password') | default('') }}"
<% if (jasperAdditionalDataSources) { -%>
  <%_ for (dsIndex of jasperAdditionalDataSources.split(',').keys()) { -%>
    jasper_ds_<%= dsIndex+1 %>_url: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_<%= dsIndex+1 %>_url') | default('') }}"
    jasper_ds_<%= dsIndex+1 %>_user: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_<%= dsIndex+1 %>_user') | default('') }}"
    jasper_ds_<%= dsIndex+1 %>_password: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_ds_<%= dsIndex+1 %>_password') | default('') }}"
  <%_ } -%>
<% } -%>
    jasper_deployer_url: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_deployer_url') | default('') }}"
    jasper_deployer_user: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_deployer_user') | default('') }}"
    jasper_deployer_password: "{{ lookup('ansible.builtin.env', 'PODMAN_cfg_jasper_deployer_password') | default('') }}"

    # To add more datasource templates, update jasperAdditionalDataSources with the comma separated list of additional datasources, and run the composer to generate the pipeline files from template.
    # Templates for each datasource xml must be added to playbooks/vars/templates/<%= jasperServerInstanceUpperCase %>_<%= projectNameUpperCase %>_<Datasource_Name>.xml.j2.
    # See playbooks/vars/templates/<%= jasperServerInstanceUpperCase %>_<%= projectNameUpperCase %>xml.j2 for an example.
    # Be sure to update the `jasper_ds_<INDEX>_(url|user|password)` keys in the template with the correct index in the order listed here, where <%= jasperServerInstanceUpperCase %>_<%= projectNameUpperCase %> has INDEX=0, and each row increments by one.
    # These `jasper_ds_<INDEX>_(url|user|password)` secrets must be added to Vault.
    jasper_datasource_folders:
      - <%= jasperServerInstanceUpperCase %>_<%= projectNameUpperCase %>
<% if (jasperAdditionalDataSources) { -%>
  <%_ for (dataSource of jasperAdditionalDataSources.split(',')) { -%>
      - <%= jasperServerInstanceUpperCase %>_<%= projectNameUpperCase %>_<%= dataSource.trim() %>
  <%_ } -%>
<% } -%>
    jasper_source_path: "<%= jasperSourcePath %>"
<% if (jasperPauseSeconds) { -%>
    # Increase the number of seconds to wait before requesting the import status
    jasper_pause_seconds: <%= jasperPauseSeconds -%>
<% } -%>

  tasks:
    - name: Create package
      include_role:
        name: jasper_reports
      tags: create_package

    - name: Deploy to node 1
      when: jasper_env in ["dev", "test", "prod"]
      include_role:
        name: jasper_reports
      tags: deploy_package

    - name: Deploy to node 2
      when: jasper_env in ["test", "prod"]
      include_role:
        name: jasper_reports
      vars:
        jasper_route_id: ".2"
      tags: deploy_package

    - name: Delete staging directory
      include_role:
        name: jasper_reports
      tags: delete_staging_dir
