name: Jasper reports - <%= serviceName %>

on:
  workflow_dispatch:

concurrency:
  group: jasper-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SERVICE_PROJECT: <%= projectName %>
  SERVICE_NAME: <%= serviceName %>
  JOB: buildByToken/buildWithParameters?job=<%= projectName %>/<%= serviceName %>
  URL: https://cd.io.nrs.gov.bc.ca

jobs:
  submit-deployment-job:
    name: Submit deployment job
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Submit deployment job
        run: |
          curl \
          --data-urlencode "token=${{ secrets.JENKINS_TOKEN }}" \
          --data-urlencode "githubToken=${{ secrets.GITHUB_TOKEN }}" \
          --data-urlencode "gitBranch=${{ github.ref_name }}" \
          --data-urlencode "gitTag=${{ (startsWith(github.ref, 'refs/tags/') && github.ref_name) || '' }}" \
          --data-urlencode "brokerJwt=${{ secrets.<%= brokerJwt %> }}" \
          -H "Connection: close" \
          ${{ env.URL }}/${{ env.JOB }}
      - name: Display deployment job URL
        run: |
          DEPLOYMENT_JOB_URL="${{ env.URL }}/job/${{ env.SERVICE_PROJECT }}/job/${{ env.SERVICE_NAME }}/"
          echo "Deployment job URL: ${DEPLOYMENT_JOB_URL}"
      - name: Keep GH token alive
        run: sleep 90s
        shell: bash
