name: 'Deploy Jasper Report Pipeline - <%= projectName %>'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, test, prod)'
        required: true
        type: choice
        options:
          - development
          - test
          - production
concurrency:
  group: run-jasper-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  preflight:
    name: Preflight
    uses: ./.github/workflows/preflight.yaml
    with:
      preflight_context: deploy-jasper
    secrets:
      token: ${{ secrets.<%= brokerJwt %> }}

  deploy-development:
    name: Deploy to development
    uses: ./.github/workflows/<%= jasperReportsWorkflowFile %>
    needs: preflight
    with:
      environment: development
    secrets: inherit
    if: |
      github.event.inputs.environment == 'development' ||
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'

  deploy-test:
    name: Deploy to test
    needs: deploy-development
    uses: ./.github/workflows/<%= jasperReportsWorkflowFile %>
    with:
      environment: test
    secrets: inherit
    if: |
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'

  deploy-production:
    name: Deploy to production
    needs: deploy-test
    uses: ./.github/workflows/<%= jasperReportsWorkflowFile %>
    with:
      environment: production
    secrets: inherit
    if: github.event.inputs.environment == 'production'
