#!/usr/bin/env bash

# Service-specific environment configuration
#
# THIS FILE IS GENERATED BY THE COMPOSER AND USED BY THE PIPELINE - MODIFICATION WILL BE OVERWRITTEN
#
# NOTE: This file should not be sourced directly. It is automatically sourced by env.sh
#       after validating the catalog-info.yaml and setting up Vault authentication.
#       Use: source env.sh [PATH] [--skip-vault] instead
#

# Check for --skip-vault flag
SKIP_VAULT=false
if [[ "${1:-}" == "--skip-vault" ]]; then
  SKIP_VAULT=true
fi

# Service-specific environment variables
export PROJECT_NAME="<%= projectName %>"
export SERVICE_NAME="<%= serviceName %>"
export PACKAGE_REPO="<%= artifactRepositoryPath %>"

<% if (pomRoot) { -%>
# Maven build configuration
export POM_ROOT="<%= pomRoot %>"
export MAVEN_ARGS="--file $POM_ROOT"
<% } -%>

<% if (toolsLocalBuildSecrets) { %>
# Only fetch vault secrets if --skip-vault is not set
if [[ "$SKIP_VAULT" == false ]]; then
<% for (const secret of toolsLocalBuildSecrets.split(',')) { -%>
  export <%= secret.toUpperCase() %>=$(vault kv get -field=<%= secret.toLowerCase() %> "apps/tools/${PROJECT_NAME}/${SERVICE_NAME}")
<% } -%>
fi
<% } %>