#!/usr/bin/env bash

# Setup build environment for service
#
# THIS FILE IS GENERATED BY THE COMPOSER AND USED BY THE PIPELINE - MODIFICATION WILL BE OVERWRITTEN
#
# Usage:
#   source env.sh [tools|local] [PATH] [--skip-vault]
#
# Arguments:
#   tools|local   Development environment mode (default: tools)
#                 - tools: Use env-tools.sh for build-specific configuration
#                 - local: Use env-local.sh for local deployment configuration
#   PATH          Path to directory containing catalog-info.yaml (default: current directory)
#   --skip-vault  Skip Vault authentication (for CI/CD or offline builds)
#
# Examples:
#   source env.sh                          # Load from current dir, tools mode
#   source env.sh local                    # Load from current dir, local mode
#   source env.sh tools ./backend          # Load from ./backend, tools mode
#   source env.sh tools --skip-vault       # Load from current dir, skip Vault
#
# This script:
#   1. Validates that the PATH catalog file is a component (kind: Component)
#   2. Authenticates with Knox Vault (unless --skip-vault specified)
#   3. Sources optional PATH/env-tools.sh (tools mode) or PATH/env-local.sh (local mode)
#
# Environment variables set:
#   VAULT_ADDR    Knox Vault address
#   VAULT_TOKEN   Authentication token (if not --skip-vault)
#   Plus any additional variables from PATH/env-tools.sh or PATH/env-local.sh

# Parse parameters
ENV_MODE="tools"  # Default to tools mode
TARGET_PATH="."
SKIP_VAULT=false

# Check first parameter for mode
if [[ "${1:-}" == "local" || "${1:-}" == "tools" ]]; then
  ENV_MODE="${1}"
  shift
fi

# Check remaining parameters for path and flags
while [[ $# -gt 0 ]]; do
  case "${1}" in
    --skip-vault)
      SKIP_VAULT=true
      shift
      ;;
    *)
      TARGET_PATH="${1}"
      shift
      ;;
  esac
done

# Default path if not provided
TARGET_PATH="${TARGET_PATH:-.}"

# Check if catalog-info.yaml exists
CATALOG_FILE="${TARGET_PATH}/catalog-info.yaml"
if [[ ! -f "$CATALOG_FILE" ]]; then
  echo "Error: catalog-info.yaml not found at ${TARGET_PATH}" >&2
  return 1 2>/dev/null || exit 1
fi

# Check if kind is Component
KIND=$(grep "^kind:" "$CATALOG_FILE" | head -1 | sed 's/\w*kind: *//; s/ *#.*//')
if [[ "$KIND" != "Component" ]]; then
  echo "Error: catalog-info.yaml kind is '${KIND}', expected 'Component'" >&2
  return 1 2>/dev/null || exit 1
fi

export VAULT_ADDR="https://knox.io.nrs.gov.bc.ca"
# Check if VAULT_TOKEN is already valid, otherwise login (unless --skip-vault)
if [[ "$SKIP_VAULT" == false ]]; then
  if [[ -z "${VAULT_TOKEN:-}" ]] || ! vault token lookup &>/dev/null 2>&1; then
    export VAULT_TOKEN=$(vault login -method=oidc -format json 2>/dev/null | jq -r '.auth.client_token')
  fi
fi

# Source environment file from target path
if [[ "$ENV_MODE" == "local" ]]; then
  # Local mode: use env-local.sh if available
  ENV_FILE="${TARGET_PATH}/env-local.sh"
else
  # Tools mode: use env-tools.sh if available
  ENV_FILE="${TARGET_PATH}/env-tools.sh"
fi

if [[ -f "$ENV_FILE" ]]; then
  if [[ "$SKIP_VAULT" == true ]]; then
    source "$ENV_FILE" --skip-vault
  else
    source "$ENV_FILE"
  fi
fi
