name: Check build artifact

on:
  workflow_call:
    inputs:
      build_workflow:
        description: "Build workflow used to validate the build artifact."
        default: ''
        type: string
        required: true
permissions: {}

jobs:
  check-build-artifact:
    name: Check build artifact
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Check build artifact
        shell: bash
        run: |
          RESPONSE=$(curl -s "https://api.github.com/repos/<%= gitHubProjectSlug %>/actions/workflows/build-release.yaml/runs?head_sha=${{ github.sha }}&branch=${{ github.ref_name }}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json")
          if [[ ${{ inputs.build_workflow }} == "build-release.yaml" ]]; then
            { read -r BUILD_ACTION_NAME; read -r BUILD_ACTION_STATUS; read -r BUILD_ACTION_URL; } < <(jq -r '.workflow_runs | sort_by(.run_number) | reverse | .[0] | .name // "", .conclusion // "", .html_url // ""' <<< "$RESPONSE")
          else
            # lookup monorepo build status by job id
            { read -r BUILD_ACTION_ID; } < <(jq -r '.workflow_runs | sort_by(.run_number) | reverse | .[0] | .id // ""' <<< "$RESPONSE")
            if [[ "$BUILD_ACTION_ID" != "" ]]; then
              JOB_RESPONSE=$(curl -s "https://api.github.com/repos/<%= gitHubProjectSlug %>/actions/runs/$BUILD_ACTION_ID/jobs" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github+json")
              SERVICE_NAME="${{ inputs.build_workflow }}"
              # trim SERVICE_NAME from build_workflow (ex. build-release-<service_name>.yaml --> <service_name>)
              # trim first 14 characters (build-release-) and last 5 characters (.yaml)
              SERVICE_NAME="${SERVICE_NAME:14:$((${#SERVICE_NAME} - 19))}"
              { read -r BUILD_ACTION_NAME; read -r BUILD_ACTION_STATUS; read -r BUILD_ACTION_URL; } < <(jq -r '.jobs | map(select(.name == "'"$SERVICE_NAME"' / Build and publish")).[] | .name // "", .conclusion // "", .html_url // ""' <<< "$JOB_RESPONSE")
            fi
          fi
          if [[ "$BUILD_ACTION_URL" != "" ]]; then
            echo "Found build action url: $BUILD_ACTION_URL"
          else
            echo "Unable to parse build action url."
          fi
          if [[ "$BUILD_ACTION_STATUS" != "success" ]]; then
            echo "::error ::Last '${BUILD_ACTION_NAME:-${{ inputs.build_workflow }}}' was not 'success' or does not exist."
            echo "This deploy was triggered on ${{ github.ref_name }} branch with the ${{ github.sha }} commit hash which does not have a successful build. Please examine the build output and ensure a build is successful before triggering a deploy."
            exit 1
          fi
