name: Check token expiration

on:
  workflow_call:
    inputs:
      url:
        description: "The Broker URL"
        default: https://broker.io.nrs.gov.bc.ca
        type: string
    secrets:
      token:
        description: "The Broker token"
        required: true
permissions: {}

jobs:
  check-jwt:
    name: Check broker token
    runs-on: ubuntu-latest

    steps:
      - name: Check token expiration
        shell: bash
        run: |
          RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}" -X 'GET' \
            ${{ inputs.url }}/v1/health/token-check \
            -H 'accept: */*' \
            -H 'Authorization: Bearer '"${{ secrets.token }}"'' \
            )

          if [ "$RESPONSE_CODE" -eq 401 ]; then
            echo "Unauthorized (401)"
            exit 1
          elif [ "$RESPONSE_CODE" -eq 403 ]; then
            echo "Invalid JWT: Block list has match"
            exit 1
          else
            echo "Response code: $RESPONSE_CODE"
          fi