name: Preflight

on:
  workflow_call:
    secrets:
      token:
        description: "The Broker token"
        required: true
    inputs:
      release_check:
        description: "Whether to run the release package check"
        required: false
        default: false
        type: boolean
      project_name:
        description: "The project name"
        type: string
        default: ""
        required: false
      service_name:
        description: "The service name"
        type: string
        default: ""
        required: false
permissions: {}

jobs:
  check-jwt:
    name: Check broker token
    uses: ./.github/workflows/check-token.yaml
    secrets:
      token: ${{ secrets.token }}

  check-release-package:
    name: Check release package
    uses: ./.github/workflows/check-release-package.yaml
    secrets:
      token: ${{ secrets.token }}
    with:
      service_name: ${{ inputs.service_name }}
      project_name: ${{ inputs.project_name }}
    if: ${{ inputs.release_check == true && github.ref_type == 'tag' }}
