name: 'Deploy pipeline - <%= serviceName %>'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy artifact from previous selection until this environment'
        required: true
        type: choice
        options:
          - development
          - test
          - production
      config_branch:
        description: 'Use playbook folder from different branch (optional)'
        required: false
        type: string

permissions:
  contents: read
  packages: read
  actions: read
  pull-requests: read

jobs:
  preflight:
    name: Preflight
    uses: ./.github/workflows/preflight.yaml
    with:
      catalog_info: <%= relativePath %><%= relativePath ? '/' : '' %>catalog-info.yaml
      preflight_context: deploy
      build_workflow: <%= buildWorkflowFile %>
    secrets:
      token: ${{ secrets.<%= brokerJwt %> }}

  deploy-development:
    name: Deploy to development
    uses: ./.github/workflows/<%= deployWorkflowFile %>
    needs: preflight
    with:
      environment: development
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: |
      github.event.inputs.environment == 'development' ||
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'

  deploy-test:
    name: Deploy to test
    needs: deploy-development
    uses: ./.github/workflows/<%= deployWorkflowFile %>
    with:
      environment: test
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: |
      github.event.inputs.environment == 'test' ||
      github.event.inputs.environment == 'production'

  deploy-production:
    name: Deploy to production
    needs: deploy-test
    uses: ./.github/workflows/<%= deployWorkflowFile %>
    with:
      environment: production
      config_branch: ${{ github.event.inputs.config_branch }}
    secrets: inherit
    if: github.event.inputs.environment == 'production'
