---
- name: <%= projectName %>/<%= serviceName %>
  hosts: "{{ tomcat_server_hosts }}"
  collections:
    - polaris.deploy
  vars_files:
    - "vars/standard/all.yaml"
    - "vars/standard/{{env_vars}}.yaml"
    - "vars/custom/all.yaml"
    - "vars/custom/{{env_vars}}.yaml"

  roles:
    # prepare the installation environment by creating the necessary folders
    - role: create_project_directories

    # Establish the port number
    - role: port_manager

    # individual JDK installation
    - role: jdk

    # create a self signed certificate to allow for HTTPS
    - role: self_signed_cert

    # install & configure the Tomcat container
    - role: tomcat

    # deploy the webapp
    - role: webapp
      vars:
        webapp_war:
          context: "{{ context }}"
        webapp_root_log_level: "{{ log_level_root | default('INFO') }}"
        proxy_env: "{{ env_vars }}"

    # create a WebADE connection jar for the container
    - role: webade_connection_jar
      # Uncomment the following line if using the MOF Webade datastore
      # vars:
      #   webade_datastore: "ca.bc.gov.webade.mof.MOFOrganizationDatastore"
      become: yes
      become_user: "{{ polaris_install_user }}"

  tasks:
    # The following task is an example for adding custom webapp configuration files
    # You can modify it according to your needs or remove it if custom configuration is not needed
    - name: configure nonstandard files
      template:
        src: "{{ playbook_dir }}/templates/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0775"
      become: yes
      become_user: "{{ polaris_install_user }}"
      with_items:
        - {
            src: "web.xml.j2",
            dest: "{{ polaris_apps_service_install_home }}/webapps/{{ alt_app_dir_name | default(context) }}/WEB-INF/web.xml"
          }
